#!/usr/bin/env python3
"""Build assets/ships/<ship>/atlas_manifest.json from the renders manifest.

The render pipeline writes assets/ships/<ship>/renders/manifest.json — that file
is the authoritative list of authored (az, el) pairs. The engine, on the other
hand, loads assets/ships/<ship>/atlas_manifest.json and picks the nearest frame
by angle.

This tool builds the engine-facing manifest by walking the render manifest and
naming the matching sprite outputs produced by tools/batch_generate_ship_sprites.py.
It emits paths to *_clean.png as both `sprite` and `sprite_uncropped` so a
follow-up run of tools/center_ship_atlas_cells.py can normalise frame sizes and
overwrite `sprite` with the *_cell.png variant — the engine never needs to know
which step authored the file, just where to read it from.

Conventions:
- All image paths are repo-relative under assets/ (engine strips the prefix).
- Frames missing from disk are dropped with a warning so the engine doesn't try
  to load empty sprites.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]


def asset_rel(p: Path) -> str:
    return str(p.relative_to(REPO / "assets")).replace("\\", "/")


def sprite_paths_for(ship: str, render_stem: str) -> dict[str, Path]:
    base = REPO / "assets" / "ships" / ship / "sprites" / f"{render_stem}_newmodel_512"
    return {
        "raw":     base.with_name(base.name + ".png"),
        "clean":   base.with_name(base.name + "_clean.png"),
        "preview": base.with_name(base.name + "_clean_on_black.png"),
    }


def build_manifest(ship: str) -> dict:
    renders_path = REPO / "assets" / "ships" / ship / "renders" / "manifest.json"
    if not renders_path.exists():
        raise SystemExit(f"render manifest not found: {renders_path}")

    renders = json.loads(renders_path.read_text(encoding="utf-8"))
    samples_in = renders.get("samples", [])
    elevations = sorted({float(s["el"]) for s in samples_in})
    azimuths   = sorted({float(s["az"]) for s in samples_in})

    samples_out: list[dict] = []
    dropped = 0
    for s in samples_in:
        stem = Path(s["file"]).stem  # e.g. tarsus_az022p5_el-060
        paths = sprite_paths_for(ship, stem)
        if not paths["clean"].exists():
            print(f"  drop (no clean sprite): {stem}")
            dropped += 1
            continue
        samples_out.append({
            "az": float(s["az"]),
            "el": float(s["el"]),
            "sprite":  asset_rel(paths["clean"]),
            "raw":     asset_rel(paths["raw"]),
            "preview": asset_rel(paths["preview"]) if paths["preview"].exists() else asset_rel(paths["clean"]),
        })

    manifest = {
        "ship": ship,
        "kind": "view_sphere_sprite_atlas",
        "forward_axis": "+Z",
        "up_axis": "+Y",
        "azimuth_degrees":   azimuths,
        "elevation_degrees": elevations,
        "pixel_grid": 512,
        "palette_size": 40,
        "samples": samples_out,
        "notes": (
            "Generated by tools/build_ship_atlas_manifest.py from "
            "renders/manifest.json + sprites/*. Run tools/center_ship_atlas_cells.py "
            "afterwards to normalise frame sizes."
        ),
    }
    if dropped:
        print(f"warning: dropped {dropped} samples lacking clean sprite output")
    return manifest


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--ship", default="tarsus")
    ap.add_argument("--out",  default=None,
                    help="Override output path (default: assets/ships/<ship>/atlas_manifest.json)")
    args = ap.parse_args()

    out_path = Path(args.out) if args.out else REPO / "assets" / "ships" / args.ship / "atlas_manifest.json"
    manifest = build_manifest(args.ship)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(f"{args.ship}: wrote {len(manifest['samples'])} samples")
    print(f"  azimuths:   {manifest['azimuth_degrees']}")
    print(f"  elevations: {manifest['elevation_degrees']}")
    print(f"updated {out_path}")


if __name__ == "__main__":
    main()
