#!/usr/bin/env python3
"""
gen_icosphere.py — emit an icosphere OBJ with UVs suitable for planet-style
equirectangular textures.

Starts from a 20-triangle icosahedron, subdivides each triangle into 4 a
configurable number of times (4 subdivisions = 5120 triangles, plenty for
a smooth-looking body at any sensible distance), and projects vertices
back onto the unit sphere after each subdivision.

UVs are spherical (atan2 for longitude, asin for latitude) with the
classic "texture-seam" fix: any triangle that straddles the u=0/u=1 seam
gets duplicated vertices with shifted UVs so bilinear filtering doesn't
pull across the seam.

Run from the repo root:
    python3 tools/gen_icosphere.py --subdivs 4 --out assets/meshes/planet_sphere.obj
"""

from __future__ import annotations

import argparse
import math
import os
import sys
from dataclasses import dataclass


# ----------------------------------------------------------------------
# 12 canonical icosahedron vertices + 20 triangle indices.
# ----------------------------------------------------------------------
def icosahedron():
    t = (1.0 + math.sqrt(5.0)) / 2.0
    verts = [
        (-1,  t,  0), ( 1,  t,  0), (-1, -t,  0), ( 1, -t,  0),
        ( 0, -1,  t), ( 0,  1,  t), ( 0, -1, -t), ( 0,  1, -t),
        ( t,  0, -1), ( t,  0,  1), (-t,  0, -1), (-t,  0,  1),
    ]
    faces = [
        (0, 11, 5), (0, 5, 1),  (0, 1, 7),   (0, 7, 10), (0, 10, 11),
        (1, 5, 9),  (5, 11, 4), (11, 10, 2), (10, 7, 6), (7, 1, 8),
        (3, 9, 4),  (3, 4, 2),  (3, 2, 6),   (3, 6, 8),  (3, 8, 9),
        (4, 9, 5),  (2, 4, 11), (6, 2, 10),  (8, 6, 7),  (9, 8, 1),
    ]
    # Normalise to unit sphere.
    norm = [_unit(v) for v in verts]
    return norm, faces


def _unit(v):
    x, y, z = v
    L = math.sqrt(x * x + y * y + z * z)
    return (x / L, y / L, z / L)


def subdivide(verts, faces):
    """Each triangle → 4 triangles. Midpoints pushed back to the sphere."""
    cache: dict[tuple[int, int], int] = {}

    def midpoint(a, b):
        key = (min(a, b), max(a, b))
        if key in cache:
            return cache[key]
        ax, ay, az = verts[a]
        bx, by, bz = verts[b]
        verts.append(_unit(((ax + bx) / 2, (ay + by) / 2, (az + bz) / 2)))
        idx = len(verts) - 1
        cache[key] = idx
        return idx

    new_faces = []
    for a, b, c in faces:
        ab = midpoint(a, b)
        bc = midpoint(b, c)
        ca = midpoint(c, a)
        new_faces.extend([(a, ab, ca), (b, bc, ab), (c, ca, bc), (ab, bc, ca)])
    return verts, new_faces


# ----------------------------------------------------------------------
# UV assignment.
# ----------------------------------------------------------------------
def spherical_uv(v):
    x, y, z = v
    u = 0.5 + math.atan2(z, x) / (2.0 * math.pi)
    v_ = 0.5 - math.asin(max(-1.0, min(1.0, y))) / math.pi
    return (u, v_)


def fix_seam(verts, faces):
    """
    Triangles that straddle the u=0/u=1 seam pull bilinear across half
    the texture → visible vertical garbage strip. Fix by duplicating the
    offending corner vertex and shifting its U by ±1 so the triangle's
    three UVs stay within a narrow U range.
    """
    uvs = [spherical_uv(v) for v in verts]
    new_faces = []
    for a, b, c in faces:
        u = [uvs[a][0], uvs[b][0], uvs[c][0]]
        if max(u) - min(u) > 0.5:
            new_tri = []
            for i, vi in enumerate((a, b, c)):
                if u[i] < 0.25:
                    # Clone this vertex with U shifted into [1.0, 1.25].
                    verts.append(verts[vi])
                    uvs.append((uvs[vi][0] + 1.0, uvs[vi][1]))
                    new_tri.append(len(verts) - 1)
                else:
                    new_tri.append(vi)
            new_faces.append(tuple(new_tri))
        else:
            new_faces.append((a, b, c))
    return verts, uvs, new_faces


# ----------------------------------------------------------------------
# OBJ emission.
# ----------------------------------------------------------------------
def write_obj(path, verts, uvs, faces):
    with open(path, "w") as f:
        f.write("# icosphere — generated by tools/gen_icosphere.py\n")
        for x, y, z in verts:
            f.write(f"v {x:.6f} {y:.6f} {z:.6f}\n")
        for u, v_ in uvs:
            f.write(f"vt {u:.6f} {v_:.6f}\n")
        # Normals on a unit sphere = positions, so same index for v and n.
        for x, y, z in verts:
            f.write(f"vn {x:.6f} {y:.6f} {z:.6f}\n")
        for a, b, c in faces:
            # OBJ is 1-indexed; all three ref indices match in our layout.
            f.write(
                f"f {a+1}/{a+1}/{a+1} {b+1}/{b+1}/{b+1} {c+1}/{c+1}/{c+1}\n"
            )


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--subdivs", type=int, default=4,
                    help="Icosahedron subdivisions (0 = 20 tris, 4 = 5120)")
    ap.add_argument("--out", required=True, help="Output .obj path")
    args = ap.parse_args(argv)

    verts, faces = icosahedron()
    for _ in range(args.subdivs):
        verts, faces = subdivide(verts, faces)

    verts, uvs, faces = fix_seam(verts, faces)

    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    write_obj(args.out, verts, uvs, faces)
    print(f"[gen_icosphere] wrote {args.out}: "
          f"{len(verts)} verts, {len(faces)} tris")


if __name__ == "__main__":
    sys.exit(main())
